spring.application.name=SigoAPP

# Configuracion de Oracle
spring.datasource.url=jdbc:oracle:thin:@//noproddldbs01-public-phx.infra.arqbs.com:1621/DB0617_NOPRODDLDBS01_PDBDEV02.paas.oracle.com
spring.datasource.username=${DB_USERNAME:SRFPNACUA}
spring.datasource.password=${DB_PASSWORD:y7x_8WGhtiWm6_JbyrJ0}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081
# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
# Configuracion de Hibernate / JPA
##spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Developer Mode
security.developer-mode=true
app.features.envio-correo=false
# mail config
#uxdy mfll onrw grdq
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

