spring.application.name=SigoAPP

# Configuracion de Oracle
spring.datasource.url=jdbc:oracle:thin:@//152.70.132.151:1521/pdbeehpdev6.eehpsubnet.eehpvcn.oraclevcn.com
spring.datasource.username=${DB_USERNAME:FIINTE}
spring.datasource.password=${DB_PASSWORD:FIINTE}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081

# HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Configuracion de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
